FROM node

RUN apt-get update -qq && apt-get install -y build-essential
RUN apt-get install -y ruby
RUN gem install sass

RUN mkdir /src

RUN npm install -g gulp bower

WORKDIR /src
ADD app/package.json /src/package.json
RUN npm install

ADD app/bower.json /src/app/bower.json
RUN cd /src/app && bower install --allow-root

EXPOSE 3000
EXPOSE 35729

CMD ["node", "main.js"]
