version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
        - "./app:/src/app"
    command: gulp --gulpfile app/gulpfile.js
    ports:
    - "3000:3000"
    - "35729:35729"
