version: '2'
services:
  mongo:
    image: mongo
  node:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
        - "./app:/app"
    command: "/bin/sh bin/start-dev"
    links:
      - mongo:mongo
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - MONGODB_URL=mongodb://mongo/parko-project
      - DISABLE_NOTIFIER=true
