version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
        - "./server:/src/server"
    command: gulp --gulpfile server/gulpfile.js
    ports:
    - "3000:3000"
    - "35729:35729"