FROM node

RUN apt-get update -qq && apt-get install -y build-essential
RUN apt-get install -y ruby
RUN gem install sass

RUN mkdir /app

RUN npm install -g gulp bower

WORKDIR /app

EXPOSE 3000
EXPOSE 35729

CMD ["npm", "start"]
